name: publish-images

inputs:
  push-to-docker:
    description: 
    default: true
    type: boolean
  
  push-to-prime:
    description: 
    default: true
    type: boolean

  make-target:
    description:
    default: push-image
    type: string

  image:
    description:
    required: true
    type: string

runs:
  using: composite

  steps:
  # Login to all registries before starting the pushing process.
  # Short-circuit if either fails. This should decrease the likelihood
  # of one registry getting updated while the other didn't.
  - name: Login to registry [DockerHub]
    if: ${{ inputs.push-to-docker }}
    uses: docker/login-action@v3
    with:
      registry: ${{ vars.PUBLIC_REGISTRY }}
      username: ${{ secrets.PUBLIC_REGISTRY_USERNAME }}
      password: ${{ secrets.PUBLIC_REGISTRY_PASSWORD }}

  - name: Login to registry [Prime]
    if: ${{ inputs.push-to-prime }}
    uses: docker/login-action@v3
    with:
      registry: ${{ secrets.PRIME_REGISTRY }}
      username: ${{ secrets.PRIME_REGISTRY_USERNAME }}
      password: ${{ secrets.PRIME_REGISTRY_PASSWORD }}

  - name: Setup QEMU
    uses: docker/setup-qemu-action@v3
  - name: Setup Docker Buildx
    uses: docker/setup-buildx-action@v3
  - name: Install Cosign
    uses: sigstore/cosign-installer@v3.5.0

  - name: Set environment variables
    run: |
      echo "${{ inputs.env_vars }}" | while read line; do
        export "$line"
      done

  - name: Build and push image [DockerHub]
    if: ${{ inputs.push-to-docker }}
    run: |
      make ${{ inputs.make-target }}
    env:
      REPO: ${{ vars.PUBLIC_REGISTRY }}/${{ vars.PUBLIC_REGISTRY_REPO }}

  - name: Build and push image [Prime]
    if: ${{ inputs.push-to-prime }}
    run: |
      IID_FILE=$(mktemp)
      export IID_FILE_FLAG="--iidfile ${IID_FILE}"
      
      make ${{ inputs.make-target }}
      cosign sign --fulcio-url=${FULCIO_URL} --rekor-url=${REKOR_URL} --oidc-provider=github-actions --yes "${REPO}/${{ inputs.image }}@$(head -n 1 ${IID_FILE})"
    env:
      REPO: ${{ secrets.PRIME_REGISTRY }}/${{ secrets.PRIME_REGISTRY_REPO }}
      # Lines below are for test only and will be removed for final version.
      # https://docs.sigstore.dev/system_config/public_deployment/#staging-instance
      FULCIO_URL: https://fulcio.sigstore.dev
      REKOR_URL: https://rekor.sigstore.dev
