name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # To sign the images.
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Publish multi-arch manifest
      uses: ./.github/actions/docker-build@v1
      with:
        image: security-scan

    - name: Publish amd64 manifest
      uses: ./.github/actions/docker-build@v1
      with:
        image: security-scan
        env_vars: |
          TAG="${{ github.ref_name }}-amd64"
          TARGET_PLATFORMS=linux/amd64

    - name: Publish arm64 manifest
      uses: ./.github/actions/docker-build@v1
      with:
        image: security-scan
        env_vars: |
          TAG="${{ github.ref_name }}-arm64"
          TARGET_PLATFORMS=linux/arm64
