name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write # To sign the provenance.
  contents: write # To upload assets to release.
  packages: write # To upload container images.
  actions: read # To read the workflow path.

jobs:

  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        # registry: docker.io
        # username: ${{ secrets.REGISTRY_USERNAME }}
        # password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Checkout code
      uses: actions/checkout@v4
  
    # TODO: Sign all images or only manifest?
    - name: Push and Sign multi-arch manifests
      run: |
        make image-push-and-sign
        TAG="${TAG}-amd64" TARGET_PLATFORMS=linux/amd64 make push-image
        TAG="${TAG}-arm64" TARGET_PLATFORMS=linux/arm64 make push-image
      env:
        TAG: ${{ github.ref_name }}
        REPO: ghcr.io/${{ github.actor }}
