name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:

  publish-public:
    runs-on: ubuntu-latest
    
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.PUBLIC_REGISTRY }}
        username: ${{ secrets.PUBLIC_REGISTRY_USERNAME }}
        password: ${{ secrets.PUBLIC_REGISTRY_PASSWORD }}
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Build and push all image variations
      run: |
        make image-push
        TAG="${TAG}-amd64" TARGET_PLATFORMS=linux/amd64 make image-push
        TAG="${TAG}-arm64" TARGET_PLATFORMS=linux/arm64 make image-push
      env:
        TAG: ${{ github.ref_name }}
        REPO: ${{ vars.PUBLIC_REGISTRY }}/${{ vars.PUBLIC_REGISTRY_REPO }}


  publish-prime:
    runs-on: ubuntu-latest
    needs: publish-public

    strategy:
      matrix:
        include:
          - tag: ${{ github.ref_name }}
            platforms: linux/amd64,linux/arm64
          - tag: ${{ github.ref_name }}-arm64
            platforms: linux/arm64
          - tag: ${{ github.ref_name }}-amd64
            platforms: linux/amd64

    permissions:
      contents: write # upload bundle files
      id-token: write # for OIDC provider (a.k.a "keyless")

    steps:
    - name: Login to Prime Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.PRIME_REGISTRY }}
        username: ${{ secrets.PRIME_REGISTRY_USERNAME }}
        password: ${{ secrets.PRIME_REGISTRY_PASSWORD }}

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.5.0

    - name: Build and push Prime images
      run: |
        IID_FILE=$(mktemp)
        IID_FILE_FLAG="--iidfile ${IID_FILE}" \
          make image-push

        cosign sign --output-payload="${TAG}.bundle" --oidc-provider=github-actions --yes "${IMAGE_NO_TAG}@$(head -n 1 ${IID_FILE})"

        gh release upload "${TAG}" "${TAG}.bundle"
      env:
        TAG: ${{ matrix.tag }}
        TARGET_PLATFORMS: ${{ matrix.platforms }}
        REPO: ${{ secrets.PRIME_REGISTRY }}/${{ secrets.PRIME_REGISTRY_REPO }}
        IMAGE_NO_TAG: ${{ secrets.PRIME_REGISTRY }}/${{ secrets.PRIME_REGISTRY_REPO }}/security-scan
        GH_TOKEN: ${{ github.token }}
