name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

# GitHub Settings and example values:
#
# org level vars:
#   - PUBLIC_REGISTRY: docker.io
#   - PRIME_REGISTRY: registry.rancher.com
#   - REKOR_URL: https://rekor.sigstore.dev
#   - FULCIO_URL: https://fulcio.sigstore.dev
# repo level vars:
#   - PUBLIC_REPO: rancher
#   - PRIME_REPO: rancher-prime
# repo level secrets:
#   - PUBLIC_REGISTRY_USERNAME
#   - PUBLIC_REGISTRY_PASSWORD
#   - PRIME_REGISTRY_USERNAME
#   - PRIME_REGISTRY_PASSWORD

jobs:

  publish-public:
    runs-on: ubuntu-latest
    permissions:    
      packages: write # (Only needed for GHCR)
    
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.PUBLIC_REGISTRY }}
        # For External registries:
        # username: ${{ secrets.PUBLIC_REGISTRY_USERNAME }}
        # password: ${{ secrets.PUBLIC_REGISTRY_PASSWORD }}
        # For GHCR, to rely on workflow credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Build and push all image variations
      run: |
        make image-push
        TAG="${TAG}-amd64" TARGET_PLATFORMS=linux/amd64 make image-push
        TAG="${TAG}-arm64" TARGET_PLATFORMS=linux/arm64 make image-push
      env:
        TAG: ${{ github.ref_name }}
        REPO: ${{ vars.PUBLIC_REGISTRY }}/${{ vars.PUBLIC_REGISTRY_REPO }}

  publish-prime:
    runs-on: ubuntu-latest
    permissions:
      # The permissions below are solely for cosign:
      id-token: write # To sign the provenance.
      contents: write # To upload assets to release.
      actions: read   # To read the workflow path.
    
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.PRIME_REGISTRY }}
        username: ${{ secrets.PRIME_REGISTRY_USERNAME }}
        password: ${{ secrets.PRIME_REGISTRY_PASSWORD }}
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Push and sign multi-arch manifests
      run: |
        make image-push-and-sign
      env:
        TAG: ${{ github.ref_name }}
        REPO: ${{ vars.PRIME_REGISTRY }}/${{ vars.PRIME_REGISTRY_REPO }}
        REKOR_URL: ${{ vars.REKOR_URL }}    # Remove to fallback to sigstore's production Rekor.
        FULCIO_URL: ${{ vars.FULCIO_URL }}  # Remove to fallback to sigstore's production Fulcio.
