name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:

  publish-public:
    runs-on: ubuntu-latest
    
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.PUBLIC_REGISTRY }}
        username: ${{ secrets.PUBLIC_REGISTRY_USERNAME }}
        password: ${{ secrets.PUBLIC_REGISTRY_PASSWORD }}
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Build and push all image variations
      run: |
        make image-push
        TAG="${TAG}-amd64" TARGET_PLATFORMS=linux/amd64 make image-push
        TAG="${TAG}-arm64" TARGET_PLATFORMS=linux/arm64 make image-push
      env:
        TAG: ${{ github.ref_name }}
        REPO: ${{ vars.PUBLIC_REGISTRY }}/${{ vars.PUBLIC_REGISTRY_REPO }}


  publish-prime:
    runs-on: ubuntu-latest
    needs: publish-public

    permissions:
      contents: read
      id-token: write # for OIDC provider (a.k.a "keyless")

    steps:
    - name: Login to Prime Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.PRIME_REGISTRY }}
        username: ${{ secrets.PRIME_REGISTRY_USERNAME }}
        password: ${{ secrets.PRIME_REGISTRY_PASSWORD }}

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.5.0

    - name: Build and push Prime images
      run: |
        IID_FILE=$(mktemp)
        IID_FILE_FLAG="--iidfile ${IID_FILE}" make image-push
        cosign sign --oidc-provider=github-actions --yes "${IMAGE_NO_TAG}@$$(head -n 1 ${IID_FILE})"

        TAG="${TAG}-amd64" TARGET_PLATFORMS=linux/amd64 IID_FILE_FLAG="--iidfile ${IID_FILE}" make image-push
        cosign sign --oidc-provider=github-actions --yes "${IMAGE_NO_TAG}@$$(head -n 1 ${IID_FILE})"

        TAG="${TAG}-arm64" TARGET_PLATFORMS=linux/arm64 IID_FILE_FLAG="--iidfile ${IID_FILE}" make image-push 
        cosign sign --oidc-provider=github-actions --yes "${IMAGE_NO_TAG}@$$(head -n 1 ${IID_FILE})"
      env:
        TAG: ${{ github.ref_name }}
        REPO: ${{ secrets.PRIME_REGISTRY }}/${{ secrets.PRIME_REGISTRY_REPO }}
        IMAGE_NO_TAG: ${{ secrets.PRIME_REGISTRY }}/${{ secrets.PRIME_REGISTRY_REPO }}/security-scan
