name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # To sign the images.
    
    strategy:
      matrix:
        include:
          - tag-suffix: ""
            platforms: linux/amd64,linux/arm64
          - tag-suffix: "-arm64"
            platforms: linux/arm64
          - tag-suffix: "-amd64"
            platforms: linux/amd64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Publish manifest
      uses: ./.github/actions/rancher-publish
      with:
        image: security-scan
        tag: ${{ github.ref_name }}${{ matrix.tag-suffix }}
        platforms: ${{ matrix.platforms }}

        public-registry: ${{ vars.PUBLIC_REGISTRY }}
        public-repo: ${{ vars.PUBLIC_REGISTRY_REPO }}
        public-username: ${{ secrets.PUBLIC_REGISTRY_USERNAME }}
        public-password: ${{ secrets.PUBLIC_REGISTRY_PASSWORD }}

        prime-registry: ${{ secrets.PRIME_REGISTRY }}
        prime-repo: ${{ secrets.PRIME_REGISTRY_REPO }}
        prime-username: ${{ secrets.PRIME_REGISTRY_USERNAME }}
        prime-password: ${{ secrets.PRIME_REGISTRY_PASSWORD }}
