name: Release

on:
  push:
    tags:
      - 'v*'

# GitHub settings / example values:
#
# org level vars:
#   - PUBLIC_REGISTRY: docker.io
# repo level vars:
#   - PUBLIC_REGISTRY_REPO: rancher
# repo level secrets:
#   - PUBLIC_REGISTRY_USERNAME
#   - PUBLIC_REGISTRY_PASSWORD

permissions:
  contents: read

jobs:

  publish-public:
    runs-on: ubuntu-latest
    
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.PUBLIC_REGISTRY }}
        username: ${{ secrets.PUBLIC_REGISTRY_USERNAME }}
        password: ${{ secrets.PUBLIC_REGISTRY_PASSWORD }}
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Build and push all image variations
      run: |
        make image-push
        TAG="${TAG}-amd64" TARGET_PLATFORMS=linux/amd64 make image-push
        TAG="${TAG}-arm64" TARGET_PLATFORMS=linux/arm64 make image-push
      env:
        TAG: ${{ github.ref_name }}
        REPO: ${{ vars.PUBLIC_REGISTRY }}/${{ vars.PUBLIC_REGISTRY_REPO }}
