name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # To sign the images.
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Publish multi-arch manifest
      uses: ./.github/actions/rancher-publish
      with:
        image: security-scan

        public-registry: ${{ vars.PUBLIC_REGISTRY }}
        public-repo: ${{ vars.PUBLIC_REGISTRY_REPO }}
        public-username: ${{ secrets.PUBLIC_REGISTRY_USERNAME }}
        public-password: ${{ secrets.PUBLIC_REGISTRY_PASSWORD }}

        prime-registry: ${{ secrets.PRIME_REGISTRY }}
        prime-repo: ${{ secrets.PRIME_REGISTRY_REPO }}
        prime-username: ${{ secrets.PRIME_REGISTRY_USERNAME }}
        prime-password: ${{ secrets.PRIME_REGISTRY_PASSWORD }}

    - name: Publish amd64 manifest
      uses: ./.github/actions/rancher-publish
      with:
        image: security-scan
        env_vars: |
          TAG="${{ github.ref_name }}-amd64"
          TARGET_PLATFORMS=linux/amd64

        public-registry: ${{ vars.PUBLIC_REGISTRY }}
        public-repo: ${{ vars.PUBLIC_REGISTRY_REPO }}
        public-username: ${{ secrets.PUBLIC_REGISTRY_USERNAME }}
        public-password: ${{ secrets.PUBLIC_REGISTRY_PASSWORD }}

        prime-registry: ${{ secrets.PRIME_REGISTRY }}
        prime-repo: ${{ secrets.PRIME_REGISTRY_REPO }}
        prime-username: ${{ secrets.PRIME_REGISTRY_USERNAME }}
        prime-password: ${{ secrets.PRIME_REGISTRY_PASSWORD }}

    - name: Publish arm64 manifest
      uses: ./.github/actions/rancher-publish
      with:
        image: security-scan
        env_vars: |
          TAG="${{ github.ref_name }}-arm64"
          TARGET_PLATFORMS=linux/arm64

        public-registry: ${{ vars.PUBLIC_REGISTRY }}
        public-repo: ${{ vars.PUBLIC_REGISTRY_REPO }}
        public-username: ${{ secrets.PUBLIC_REGISTRY_USERNAME }}
        public-password: ${{ secrets.PUBLIC_REGISTRY_PASSWORD }}

        prime-registry: ${{ secrets.PRIME_REGISTRY }}
        prime-repo: ${{ secrets.PRIME_REGISTRY_REPO }}
        prime-username: ${{ secrets.PRIME_REGISTRY_USERNAME }}
        prime-password: ${{ secrets.PRIME_REGISTRY_PASSWORD }}
