name: Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    - run: make validate

  test:
    strategy:
      fail-fast: false
      matrix:
        # Run tests across all platforms, to ensure developers
        # can use any environment to run basic tests.
        platform: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.platform }}
    needs: [ validate ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
  
    - run: make test

  e2e:
    strategy:
      fail-fast: false
      matrix:
        k8s-version: [v1.27.3, v1.28.0, v1.29.0]
        platform: [ubuntu-latest]
    
    runs-on: ${{ matrix.platform }}
    needs: [ validate ]

    steps:
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Checkout code
      uses: actions/checkout@v4

    - name: E2E Tests
      env:
        KUBERNETES_VERSION: ${{ matrix.k8s-version }}
      run: make e2e

  build-image:
    runs-on: ubuntu-latest
    needs: [ validate ]

    steps:
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Image build
      run: make test-image
