name: Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
  
    - run: make test
    - run: make validate

  e2e:
    strategy:
      fail-fast: false
      matrix:
        k8s-version: [v1.27.3, v1.28.0, v1.29.0]
        platform: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.platform }}
    needs: [ validate ]

    steps:
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Checkout code
      uses: actions/checkout@v4
  
    - run: make e2e
      env:
        KUBE_VERSION: ${{ matrix.k8s-version }}   
